### ISSUE TITLE
alternate timezone 

### ISSUE THREAD

**Issue by pcause** [lfhbento/timeboxed-watchface#10]
I can select "alternate time zone" in multiple places in the interface.  I'd expect that if I have this selected twice I'd get to define 2 alternative time zones, but there is just one spot to enter.  Might consider allowing entry of additional time zones if there are multiple selections for alternative time zone.

**Comment by hussin** [comment]
Hi! That's a known limitation we have right now. I want to enable "per mode" configs in the future, but it will require some refactoring. Will look into doing it in the future releases.

**Comment by pcause** [comment]
something simple would be a great addition.  you could just have "alt-timezone-n" entries in the drop down and then n boxes to enter the values matching the specified alt-timezone.  but thanks for consideration.

**Comment by VarrinS** [comment]
+1 to this recommendation. Having two alternate time zones would be fantastic!

I'd also note that battery life is so short that it seems like a waste of one of those zones (upper/lower). That makes me wonder if it would be better in one of the corner zones. 

And on that note, if the information quantity per zone (box?) is small, I think you could fit three top/bottom zones on either the top or the bottom. For example, I think you could fit steps, battery, and heart rate all across the bottom (or top). There might be combinations that wouldn't work (maybe min/max?) with three across, but some combinations would, I think. And including battery in that list would make it possible to free up the lower line (or upper) for a second additional time zone. That'd be great for those of us who travel relentlessly. :)

**Comment by lfhbento** [comment]
It took a long while haha, but I added a second timezone selection on v5.3 :)
