### ISSUE TITLE
build errors under linux

### ISSUE THREAD

**Issue by einalex** [lfhbento/timeboxed-watchface#13]
While building the watchface under arch linux the linker stops with the error that 'setlocale' is defined in both libc.a (which is included because of your use of ctypes and toupper()) and libpebble.a.
I solved the linking error by removing the ctypes includes and replacing the calls to toupper() with code that doesn't rely on outside libs.
I would appreciate if you would fix this issue ;)

I'd supply a patch but the way I fixed it is pretty hackish and you'll certainly prefer a more sophisticated approach.

**Comment by lfhbento** [comment]
Hi! I don't know if you're still interested on this, but I've finally removed the dependencies on `time.h` and `ctype.h`. Sorry it took a long while to address the issue!
