### ISSUE TITLE
Settings doesn't applied at Android.

### ISSUE THREAD

**Issue by nsicko42** [lfhbento/timeboxed-watchface#18]
Hi!
I installed the updated app well. There seems to be no more bugs in 5.0. :)

But there is another bug.
It is a bug where the app will save any settings, but not the watchface.

You might remember that when reporting bugs in version 5.0 I told you that another app developer created another bug. It was that settings did not applied. The same bug is occurring in Timeboxed. :)

It seems to be a bug only in certain OSs.

app version 5.4
android 7.1 nugat

**Comment by nsicko42** [comment]
Sorry for late. :)

I tried to reset it as you told, but the watch face still has the same display as before.

**Comment by nsicko42** [comment]
I tried to reset it as re-install.
default setting does display clock and date only.
Then, I tried to display battery level additionally.

IT WORKS! Yeah!! :)

But any other settings doesn't work. including clock align, top left right, alternate clock, bottom left right...

**Comment by lfhbento** [comment]
That's really weird. There must be something wrong with the settings. Can
you send me screenshots of what's showing in the debug panel?

**Comment by nsicko42** [comment]
How could I send you file? do you have an any idea?

**Comment by lfhbento** [comment]
You can attach the images to this thread :) Or if you reply to this through email, I think attachments also work.

**Comment by nsicko42** [comment]
![screenshot_20171023-205849](https://user-images.githubusercontent.com/24641442/31925474-df8efa54-b8c3-11e7-8685-db775b8d510f.jpg)

**Comment by lfhbento** [comment]
Thanks for sending that! I just realized you have the Pebble Steel and not the Pebble *Time* Steel. My bad! I think I can figure it out now.

**Comment by lfhbento** [comment]
I've released a new version with a fix. The classic pebbles have very little memory, so it couldn't handle some of the new stuff I added. I removed the cryptocurrency price option and did some memory optimization and it ran fine.

**Comment by nsicko42** [comment]
It's working, it's working!
- Torvalds of Paladins

;)
