### ISSUE TITLE
Weather not working

### ISSUE THREAD

**Issue by sebacea** [lfhbento/timeboxed-watchface#24]
I switched to rebble and weather stop working. Any idea?

**Comment by Daisune** [comment]
Pixel 2 running Android 9 w/ Rebble also having the same issue. Weather worked consistently for awhile but within the last 2-3 weeks stopped updating.  (Yahoo and Darksky) Darksky doesn't show any API calls having been made.

**Comment by Daisune** [comment]
removed manual location and hit verify. Working for me now.

**Comment by sebacea** [comment]
still not working for me in Pebble 2 HR

**Comment by Daisune** [comment]
Which API are you using? Yahoo, wunderground, etc?

**Comment by sebacea** [comment]
I tried OperWeatherMap and Yahoo

**Comment by Daisune** [comment]
Email me Noah@thearkit.com
I'll shoot you my API key for dark sky see if that helps

**Comment by lfhbento** [comment]
Hi! Sorry for the delay :) And thanks for the help troubleshooting, @Daisune!

I haven't seen any issues after switching to Rebble myself, but I'm using WeatherUnderground. I'll try other providers to try to debug it and get back to you two :)

**Comment by Daisune** [comment]
No worries. We both have it working via the Dark Sky api key.

**Comment by edanaher** [comment]
I'm getting errors talking to openweathermap; the logs show a failure on the URL

> http://api.openweathermap.org/data/2.5/forecast/daily?appid=[apikey]&format=json&cnt=3&lat=[lat]&lon=[lon]

Sure enough, that URL gives me a 401 "Invalid API key".  However, I don't think it's an issue with the API key; the following URL gives back a perfectly good response:

> http://api.openweathermap.org/data/2.5/weather?q=moscow&appid=[apikey]

I'll investigate this more later, but am curious if anyone else has run into this.

**Comment by edanaher** [comment]
I figured out the problem - that `forecast/daily` route is the [16 day forecast](https://openweathermap.org/forecast16), which [isn't available](https://openweathermap.org/price) for free accounts (which is what I got).  It looks like the [five day forecast](https://openweathermap.org/forecast5) should suffice for Timeboxed's needs; I'll try to get that working and hopefully have a PR up later this week (if no one beats me to it).

**Comment by jendrush** [comment]
@lfhbento Do you have working Weather Underground provider? Mine stopped working.

**Comment by lfhbento** [comment]
Hi everyone! Sorry, I've been insanely busy and couldn't get to investigate this issue. Weather Underground also stopped working for me. I've been using DarkSky in the meantime, but I'll see if I can work on a fix this weekend for both WU and OWM :)

**Comment by jendrush** [comment]
@lfhbento Thank you. I am using WU becouse i have my own pws.

**Comment by GJHmf** [comment]
@lfhbento Isn't the WU issue simply because they pulled the free API earlier in the year?

**Comment by jendrush** [comment]
@lfhbento as @GJHmf mentioned it could be problem. I've looked at WU, and there is new API, and new Key could be generated, but this is only for PWS data providers if I understand correctly. I am person who have my own station, but majority probably not. This is new API https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit . I don't know if you have your own weather station, but if this part of Timeboxed could be easy to change i would be realy greatful.

**Comment by MaxElkins** [comment]
Has anyone managed to get this working? :)

**Comment by jendrush** [comment]
I have Garmin Forerunner 245 now, but Pebble Time still have place in my heart. There is no comparable smartwatch:(

**Comment by edanaher** [comment]
Not sure what "this" is in "getting this workign", but I'm still running my local build of TimeBoxed tweaked to make openweathermap work.  The current weather works (though one or two of the icons seem to be off, and the forecast min/max is a bit wonky).

I never did get around to cleaning it up to push, but if there's still interest, I could probably clean it up less but actually submit a PR.

**Comment by MaxElkins** [comment]
I'm refering to the weather not working, I'll be clearer next time 👍 
I'm interested in using it if you are able to submit a PR.

**Comment by edanaher** [comment]
@MaxElkins There's the PR.  No idea if it'll ever be merged, but if you have the SDK set up, you should be able to build it yourself.  I could probably also provide a pre-built package.  I actually haven't installed any apps I didn't build myself since Pebble shut down, so I'm not sure what the current normal process is.

**Comment by kerber** [comment]
Now that Darksky is getting EOL, it would be great to get the OpenWeatherMaps API working so I can keep using my favorite watch face.

**Comment by lfhbento** [comment]
I merged @edanaher's PR with the OpenWeatherMap API fix (thank you!). Closing this :)

**Comment by MaxElkins** [comment]
> @MaxElkins There's the PR. No idea if it'll ever be merged, but if you have the SDK set up, you should be able to build it yourself. I could probably also provide a pre-built package. I actually haven't installed any apps I didn't build myself since Pebble shut down, so I'm not sure what the current normal process is.

Hey sorry for late reply, would you still be able to provide a pre-built package? That would be amazing :)

**Comment by edanaher** [comment]
No worries.

This did get merged in, so my guess is that ideally @lfhbento would release it to the Rebble store, though I honestly haven't been keeping up with the current state of Pebble app distribution.

My normal process for installation is just `pebble install` from the pebble SDK, but that's a bit of a journey to get working now. I went ahead and built from master (with a fix for some obviously missing code that somehow slipped through: #29), and that produced a .pbw file, which can [apparently be sideloaded](https://www.guidingtech.com/sideload-apps-pebble-smartwatch/).  

If you want to give it a shot, it's available at http://www.edanaher.net/timeboxed-watchface.pbw .  Note that I haven't actually tested it, since I don't have a lot of time to troubleshoot right now if it breaks things.

However, I'm excited by #26, which adds phone battery level, so I may try to add that in and "release" a build, hopefully I'll be able to do that and test the sideloading process sometime this week.

**Comment by maxelkins** [comment]
Thanks @edanaher really appeciate you taking the time to sort that for me :)

As I see from the Rebble discord, they are working on allowing developers to upload new apps and update existing apps, at the moment its a manual process, @lfhbento would need to email the rebble team to get it updated.

Thanks again!

**Comment by BeriAlpha** [comment]
> removed manual location and hit verify. Working for me now.

You da real MVP. This fixed it for me.

To be specific, I was having an issue where my min/max temperature were correct, but the current weather was 74 degrees, forever. If only if were true.

**Comment by teknolai** [comment]
Thanks a lot for providing the .pbw @edanaher! Recently brought my pebble time into use again. Very happy to get the weather working again on my favourite watchface!
